server:
  port: 8081
  servlet:
    context-path: /lite-live-streaming-platform

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
    open: true  # 是否开启redis缓存
    database: 0
    host: 101.200.54.21
    port: 6379
    password: sp123456
    timeout: 6000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    cache-enabled: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


live-streaming-platform:
  jwt:
    expire: 604800  # 过期时间
    salt: cdsjklew12390d012jk1jd520dw # 加密盐
  filepath:
    dynamicFilePath: /usr/local/nginx/html/file/dynamicfile/
    dynamicFileUrl: http://ts.memorykk.cn:1936/file/dynamicfile/

logging:
  file:
    name: app.log
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n)'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} >>> [%thread] >>> %-5level >>> %logger{50} >>> %msg%n'

tencent:
  cloud:
    sms:
      SecretId: AKID2tTnqdKlwqUrxmLdePu73i7E5fz2oJXU
      SecretKey: h7G8j36tPecJkunPlrgEWXHjup79uPda
      Endpoint: sms.tencentcloudapi.com
      Region: ap-beijing
      SmsSdkAppId: 1400568669
      SignName: 张恒生活记录
      TemplateId: 1104537
  qq:
    email:
      hostname: smtp.qq.com
      from: memorykk@qq.com
      name: lite直播平台
      username: memorykk@qq.com
      password: uxyvvpohrmwhbheg
      subject: 注册邮件
