server:
  port: 8081
  servlet:
    context-path: /lite-live-streaming-platform

spring:
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://101.200.54.21:3306/lite-living-streaming?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: root123456
      # 初始化大小，最小，最大连接数, 连接超时
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      # 打开psCache，并指定大小，时隔多久检测一次需要关闭的连接， 连接最小生存时间
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      # 检测连接是否可用，不同数据库配置不同，下列oracle， mysql是通过ping，不需要配置
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #监控
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin123456
        allow:
      # 过滤器
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  redis:
    open: true  # 是否开启redis缓存
    database: 0
    host: 101.200.54.21
    port: 6379
    password: sp123456
    timeout: 6000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    cache-enabled: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  file:
    name: app.log
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n)'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} >>> [%thread] >>> %-5level >>> %logger{50} >>> %msg%n'

tencent:
  cloud:
    sms:
      SecretId: AKID2tTnqdKlwqUrxmLdePu73i7E5fz2oJXU
      SecretKey: h7G8j36tPecJkunPlrgEWXHjup79uPda
      Endpoint: sms.tencentcloudapi.com
      Region: ap-beijing
      SmsSdkAppId: 1400568669
      SignName: 张恒生活记录
      TemplateId: 1104537
  qq:
    email:
      hostname: smtp.qq.com
      from: memorykk@qq.com
      name: lite直播平台
      username: memorykk@qq.com
      password: uxyvvpohrmwhbheg
      subject: 注册邮件
