server:
  port: 8081
  servlet:
    context-path: /lite-live-streaming-platform

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
    open: true  # 是否开启redis缓存
    database: 0
    host: 101.200.54.21
    port: 6379
    password: sp123456
    timeout: 6000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml


live-streaming-platform:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    salt: cdsjklew12390d012jk1jd520dw


logging:
  file:
    name: app.log
  pattern:
    console: '%clr(%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n)'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} >>> [%thread] >>> %-5level >>> %logger{50} >>> %msg%n'
