live-streaming-platform:
  jwt:
    expire: 604800  # 过期时间
    salt: cdsjklew12390d012jk1jd520dw # 加密盐
  filepath:
    dynamicFilePath: /usr/local/nginx/html/file/dynamicfile/
    dynamicFileUrl: http://ts.memorykk.cn:1936/file/dynamicfile/
    commonFilePath: /usr/local/nginx/html/file/commonfile/
    commonFileUrl: http://ts.memorykk.cn:1936/file/commonfile/
